<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\USS.Base.Business.Interface\USS.Base.Business.Interface.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.Data.Interface\USS.Kanakkedu.Data.Interface.csproj" />
  </ItemGroup>

</Project>
