CREATE TABLE [dbo].[ACYear]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Code] NVARCHAR(20) NOT NULL, 
    [StartDate] DATE NOT NULL, 
    [EndDate] DATE NOT NULL, 
    [YearEndClosed] BIT NOT NULL, 
    [FundId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_ACYear_Fund] FOREIGN KEY ([FundId]) REFERENCES [Fund]([Id])
)
