CREATE TABLE [dbo].[ACGroup]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(500) NOT NULL, 
    [Code] NVARCHAR(50) NOT NULL, 
    [ParentId] UNIQUEIDENTIFIER NULL, 
    [FundId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_ACGroup_Fund] FOREIGN KEY ([FundId]) REFERENCES [Fund]([Id])
)
