CREATE TABLE [dbo].[Ledger]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(500) NOT NULL, 
    [Code] NVARCHAR(50) NOT NULL, 
    [ACGroupId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_Ledger_ACGroup] FOREIGN KEY ([ACGroupId]) REFERENCES [ACGroup]([Id])
)
