CREATE TABLE [dbo].[LedgerBalance]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [LedgerId] UNIQUEIDENTIFIER NOT NULL, 
    [ACYearId] UNIQUEIDENTIFIER NOT NULL, 
    [DrAmt] MONEY NOT NULL, 
    [CrAmt] MONEY NOT NULL,
    CONSTRAINT [FK_LedgerBalance_ACYear] FOREIGN KEY ([ACYearId]) REFERENCES [ACYear]([Id]),
    CONSTRAINT [FK_LedgerBalance_Ledger] FOREIGN KEY ([LedgerId]) REFERENCES [Ledger]([Id])
)
