<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\USS.Base.Extension\USS.Base.Extension.csproj" />
    <ProjectReference Include="..\USS.Base.Model\USS.Base.Model.csproj" />
    <ProjectReference Include="..\USS.Base.Web\USS.Base.Web.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.ServiceDefaults\USS.Kanakkedu.ServiceDefaults.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.Service\USS.Kanakkedu.Service.csproj" />
  </ItemGroup>

</Project>
