<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Enable OpenAPI source generator interceptors namespace to avoid CS9137 -->
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\USS.Base.APIService\USS.Base.APIService.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.Business\USS.Kanakkedu.Business.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.Data\USS.Kanakkedu.Data.csproj" />
    <ProjectReference Include="..\USS.Kanakkedu.ServiceDefaults\USS.Kanakkedu.ServiceDefaults.csproj" />
    <ProjectReference Include="..\USS.Kanakkenu.Business.Interface\USS.Kanakkedu.Business.Interface.csproj" />
  </ItemGroup>



</Project>
